Support for python 3.11, security fixes and updates (#27)
* Fixes to support python 3.11

On python 3.11 crashed with this error:
ValueError: mutable default <class 'openapi_to_fastapi.routes.RouteInfo'> for field default_get is not allowed: use default_factory

* Upgrade FastAPI to 0.95.2 and requests

- FastAPI 0.95.2 upgrades starlette to >=0.27.0 for a security release.
- Requests library in lockfile is also updated to a version that fixes some security issues

* Update datamodel-code-generator to latest version